### ISSUE TITLE
Correctif pour Docker

### ISSUE THREAD

**Issue by tfSheol** [vancharlotte/config-server-repo#1]
Hello,
J'ai trouvé quelques petits bugs : 

Dans la configuration d'Eureka

```properties
#server.port = 8761

spring.application.name=eureka-server
spring.cloud.config.uri=http://config-server:9101

# C'est bien eureka-server et non localhost, tu peux décomanter cette ligne
eureka.client.serviceUrl.defaultZone = http://eureka-server:8761/eureka/

#eureka.instance.leaseRenewalIntervalInSeconds = 3600
``` 

Ensuite j'ai corrigé quelques trucs dans le `docker-compose` 

```yml
version: '3'
services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - library-network

  db:
    image: bitnami/mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbauth
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!
    ports:
      - "6033:3306"
    networks:
      - library-network

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
    - "9101:9101"
    expose:
      - "9101"
    networks:
      - library-network

  eureka-server:
    depends_on:
      - config-server
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      WAIT_HOSTS: config-server:9101
    networks:
      - library-network

  auth-server:
    depends_on:
      - config-server
      - eureka-server
      - db
    image: auth-server
    container_name: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    expose:
      - "9191"
    environment:
      WAIT_HOSTS : db:3306, eureka-server:8761, config-server:9101
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbauth?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123!
    networks:
      - library-network

networks:
  library-network:
```

Tu avais oubliée la partie network dans ta db (et j'ai changé par la bitnami pour éviter d'autres soucis)

```yml
    networks:
      - library-network
```

Adminer permet de se connecter à ta `db` depuis ton navigateur sans utiliser `Workbench`

```yml
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - library-network
```

Voilà voilà (le résultat)

![image](https://user-images.githubusercontent.com/4259585/95925332-da72ce80-0db9-11eb-9846-ec4897b26f72.png)

auth-server
![image](https://user-images.githubusercontent.com/4259585/95925374-eb234480-0db9-11eb-97a2-da34b640a22a.png)

eureka-server
![image](https://user-images.githubusercontent.com/4259585/95925401-f8d8ca00-0db9-11eb-8a48-a07a003d8edf.png)

db
![image](https://user-images.githubusercontent.com/4259585/95925427-08581300-0dba-11eb-83d4-642522645141.png)
